export const SAVE_EMAIL_INFO = 'SAVE_EMAIL_INFO';
export const SAVE_INTRODUCER_INFO = 'SAVE_INTRODUCER_INFO';
export const SAVE_SIGNUP_INFO = 'SAVE_SIGNUP_INFO';
export const SAVE_USER_INFO = 'SAVE_USER_INFO';
export const SAVE_USER_PERSONAL_INFO = 'SAVE_USER_PERSONAL_INFO';
export const SAVE_WALLET_INFO = 'SAVE_WALLET_INFO';
